music <- read.csv('/Users/priya/Stat475/music-plusnew-sub.csv', row.names=1, stringsAsFactors=FALSE)
dim(music)
colnames(music)
head(music)
summary(music)
table(music$Type)
table(music$Artist)
bodyfat <- read.csv('/Users/priya/Stat475/bodyfat.csv')
dim(bodyfat)
colnames(bodyfat)
head(bodyfat)
pisamath <-read.csv('/Users/priya/Stat475/pisamathmeans.csv')
dim(pisamath)
summary(pisamath)
##Software
library(ggplot2)
library(GGally)